Name: Leighton Flanagan

Lab partner

## Instructions

Tuesday labs are due Friday by midnight.

For each class, download the lab and have it up and running in Jupyter when we begin the class period. This will allow you to code along with the demonstrations and be ready to go. You will be assigned a lab partner(s)to work with. Put their name above.

When you are done with your lab, upload this document to your github folder on the class site. Then submit a url link to the completed lab, along with a screenshot of your completed score for the chapter assigned in datacamp to the assignment tab in Moodle.

# Lecture 2.1

Lecture Agenda:
* Review of indexing (before warmups)
* Weekly assessment exercise
* questions

A helpful reminder of indexing in python:

![](monty_python_index.jpg)

In [7]:
title = "Monty Python"

In [8]:
# How do I print out "Monty" and "Python"?

print(title[])

print(title[]) # need one more number in index than I want to print

SyntaxError: invalid syntax. Perhaps you forgot a comma? (3747782058.py, line 3)

In [ ]:
# You don't have to specify the beginning or the end index

print(title[:5]) #start at zero

print(title[6:]) # end at the end

In [11]:
# How do I print them out using negative indices?

print(title[-6:])

print(title[-12:-7])

print(title[:-7])

Python
Monty
Monty


# Warmups 2.1

**W.1** Create a list of integers from 1-10. Name the list list1. Print the list

In [36]:
list1 = [1,2,3,4,5,6,7,8,9,10]
print(list1)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.2** Print the first element of list1. Then print the last element of list1 on the next line.

In [37]:
print(list1[0])
print(list1[-1])

1
10


**W.3** Print the second element through the ninth element of list1

In [38]:
print(list1[1:9])

[2, 3, 4, 5, 6, 7, 8, 9]


**W.4** Print the sum of the first and last elements of list1

In [39]:
print(list1[0]+list1[9])

11


**W.5** Print the product of the second and third element of list1

In [14]:
print(list1[1]*list1[2])

6


**W.6** Create a new list of only the even numbers of list1 (using indexing to pull numbers from list1). Name the new list list2. Print list2

In [15]:
list2 = [list1[1],list1[3],list1[5],list1[7],list1[9]]
print(list2)

[2, 4, 6, 8, 10]


**W.7** Print the sum of the fifth element of list1 and the fifth element of list2.

In [16]:
print(list1[4]+list2[4])

15


**W.8** Print the product of the second element of list1 and the second element of list2.

In [17]:
print(list1[1]*list2[1])

8


**W.9** Replace the first element of list1 with the integer 5. Print the list

In [18]:
list1[0] = 5
print(list1)

[5, 2, 3, 4, 5, 6, 7, 8, 9, 10]


**W.10** Replace the last element of list2 with the integer 5. Print the list

In [19]:
list2[-1] = 5
print(list2)

[2, 4, 6, 8, 5]


**W.11** Create a new list that contains list1 and list2. Name the list list3. Print the list.

In [58]:
list3 = list1 + list2
print(list3)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5]


**W.12** Create a list named list4 which contains list3 + a list of strings containing your full name.

In [42]:
list4 = list3 + ["Leighton", "Elizabeth", "Flanagan"] 
print(list4)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Leighton', 'Leighton', 'Elizabeth', 'Flanagan']


**W.13** Using the commands who and whos, print out lists of all of the variables you just created

In [22]:
who

list1	 list2	 list3	 list4	 title	 


In [23]:
whos

Variable   Type    Data/Info
----------------------------
list1      list    n=10
list2      list    n=5
list3      list    n=15
list4      list    n=18
title      str     Monty Python


**W.14** Now restart your notebook kernel and try printing out the list of variables again. What happened? Explain. 

In [ ]:
who

In [ ]:
whos

The variables do not exist, so the commands cannot identify them to print out.

**W.15** Rerun the cells above to get your variables back, you will need them in the lab below

# Lab 2.1

### Use a combination of markdown text and coding in cells below to answer the below questions.

**E.1** Complete Ch 3 of Introduction to Python in datacamp: Functions and Packages

**E.2** Explain what a function is and how you use one. Give an example.

A function is a piece of reusable code that is like a shortcut to doing a task rather than writing the code itself. An example is type(), which tells you the type of variable of what you put in the parentheses

**E.3** How do you get help with a function? Give an example. Explain what the help file is saying

You get help with a function by typing help(*function*). The help file will tell you what inputs you can type into the function, as well as what happens if some optional arguments are omitted or multiple arguments are applied.

**E.4** What is a method? How is it different from a function? Demonstrate

A method is something that is specific to the object called that is typed as an extension as such: *object*.*method*(). It is different from a function in that it only applies to the specific object it is used for. For example, you can use '.index' on a list object but not on an int object.

**E.5** Find the maximum value of one of the lists you created in the warmup exercise two ways, using both a function and a method.

In [62]:
import numpy as np
print(max(list3))
sort = list3[:]
sort.sort()
print(sort[-1])


10
10


**E.6** Repeat W.12 using a method

In [52]:
list5 = list3[:]
list5.append("Leighton")
list5.append("Elizabeth")
list5.append("Flanagan")
print(list5)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 2, 4, 6, 8, 5, 'Leighton', 'Elizabeth', 'Flanagan']


**E.7** What is a python package?

A python package is a series of code that's already written with its own functions and methods that you can install to add in to your code.

**E.8** What do you need to do to be able to use an installed package in your code? Give an example here.

You need to import the package, and typically people assign a name to it to make it easier to call up.

In [63]:
import numpy as np

**E.9** Import numpy and define an array version of list1 in W.1:   array1.

In [64]:
import numpy as np
array1 = np.array(list1)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


**E.10** Repeat W.2-W.6 using arrays

In [65]:
print(array1[0])
print(array1[-1])

1
10


In [66]:
print(array1[1:9])

[2 3 4 5 6 7 8 9]


In [67]:
print(array1[0]+array1[9])

11


In [69]:
print(array1[1]*array1[2])

6


In [74]:
array2 = np.array([array1[1], array1[3], array1[5], array1[7], array1[9]])
print(array2)

[ 2  4  6  8 10]


# Scratch